FROM node:18 as build

WORKDIR /app
COPY frontend/package.json .
RUN npm install && npx browserslist@latest --update-db

COPY frontend/ .
RUN npm run build


FROM nginx:1.25

COPY --from=build /app/dist /usr/share/nginx/html
COPY frontend/default.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
