---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wp-tls-secret
  namespace: wiki
spec:
  secretName: wp-tls-secret 
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - terzeron.com
    - fm.terzeron.com
    - api-fm.terzeron.com
