# fm.terzeron.com (frontend)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fm-frontend-route
  namespace: feedmaker
spec:
  parentRefs:
    - name: main-gateway
      namespace: traefik
  hostnames:
    - "fm.terzeron.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: fm-frontend
          port: 80

---
# api-fm.terzeron.com (backend)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fm-backend-route
  namespace: feedmaker
spec:
  parentRefs:
    - name: main-gateway
      namespace: traefik
  hostnames:
    - "api-fm.terzeron.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: fm-backend
          port: 8010

