from typing import Any

class Chrome:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, url: str) -> None: ...
    def quit(self) -> None: ...
    def close(self) -> None: ...
    @property
    def current_url(self) -> str: ...
    @property
    def page_source(self) -> str: ...
    def get_cookies(self) -> list[dict[str, Any]]: ...
    def add_cookie(self, cookie: dict[str, Any]) -> None: ...
    def set_page_load_timeout(self, timeout: float) -> None: ...
    def set_script_timeout(self, timeout: float) -> None: ...
    def execute_script(self, script: str, *args: Any) -> Any: ...
    def find_element(self, by: str, value: str) -> Any: ...
    def find_elements(self, by: str, value: str) -> list[Any]: ...
    @property
    def switch_to(self) -> Any: ...
    def __getattr__(self, name: str) -> Any: ...

def __getattr__(name: str) -> Any: ... 