from typing import Any, Callable, Tuple

def presence_of_element_located(locator: Tuple[str, str]) -> Callable[[Any], Any]: ...
def invisibility_of_element_located(locator: Tuple[str, str]) -> Callable[[Any], Any]: ...

def __getattr__(name: str) -> Any: ... 