from typing import Any, Callable, Optional, TypeVar

T = TypeVar('T')

class WebDriverWait:
    def __init__(self, driver: Any, timeout: float, **kwargs: Any) -> None: ...
    def until(self, method: Callable[[Any], T], message: str = "") -> T: ...
    def until_not(self, method: Callable[[Any], T], message: str = "") -> T: ...

def __getattr__(name: str) -> Any: ... 