from typing import Any, Optional

class WebDriverException(Exception):
    def __init__(self, msg: Optional[str] = None, **kwargs: Any) -> None: ...

class InvalidCookieDomainException(WebDriverException): ...
class TimeoutException(WebDriverException): ...

def __getattr__(name: str) -> Any: ... 