from typing import Any, Dict, List

class Options:
    def __init__(self) -> None: ...
    @property
    def arguments(self) -> List[str]: ...
    def add_argument(self, argument: str) -> None: ...
    def to_capabilities(self) -> Dict[str, Any]: ...
    def __getattr__(self, name: str) -> Any: ... 