from typing import Any, Optional

class Service:
    def __init__(self, executable_path: Optional[str] = None, **kwargs: Any) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ... 